/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather/index'
import { Route as StudentListIndexRouteImport } from './routes/student-list/index'
import { Route as StudentListAddIndexRouteImport } from './routes/student-list/add/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListIndexRoute = StudentListIndexRouteImport.update({
  id: '/student-list/',
  path: '/student-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListAddIndexRoute = StudentListAddIndexRouteImport.update({
  id: '/student-list/add/',
  path: '/student-list/add/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student-list/': typeof StudentListIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/student-list/add/': typeof StudentListAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student-list': typeof StudentListIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/student-list/add': typeof StudentListAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student-list/': typeof StudentListIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/student-list/add/': typeof StudentListAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/student-list/' | '/weather/' | '/student-list/add/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/student-list' | '/weather' | '/student-list/add'
  id: '__root__' | '/' | '/student-list/' | '/weather/' | '/student-list/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentListIndexRoute: typeof StudentListIndexRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
  StudentListAddIndexRoute: typeof StudentListAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather/'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list/': {
      id: '/student-list/'
      path: '/student-list'
      fullPath: '/student-list/'
      preLoaderRoute: typeof StudentListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list/add/': {
      id: '/student-list/add/'
      path: '/student-list/add'
      fullPath: '/student-list/add/'
      preLoaderRoute: typeof StudentListAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentListIndexRoute: StudentListIndexRoute,
  WeatherIndexRoute: WeatherIndexRoute,
  StudentListAddIndexRoute: StudentListAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
