/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather/index'
import { Route as StudentListIndexRouteImport } from './routes/student-list/index'
import { Route as CourseCatalogIndexRouteImport } from './routes/course-catalog/index'
import { Route as StudentListAddIndexRouteImport } from './routes/student-list/add/index'
import { Route as StudentListIdIndexRouteImport } from './routes/student-list/$id/index'
import { Route as CourseCatalogAddIndexRouteImport } from './routes/course-catalog/add/index'
import { Route as CourseCatalogIdIndexRouteImport } from './routes/course-catalog/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListIndexRoute = StudentListIndexRouteImport.update({
  id: '/student-list/',
  path: '/student-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCatalogIndexRoute = CourseCatalogIndexRouteImport.update({
  id: '/course-catalog/',
  path: '/course-catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListAddIndexRoute = StudentListAddIndexRouteImport.update({
  id: '/student-list/add/',
  path: '/student-list/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListIdIndexRoute = StudentListIdIndexRouteImport.update({
  id: '/student-list/$id/',
  path: '/student-list/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCatalogAddIndexRoute = CourseCatalogAddIndexRouteImport.update({
  id: '/course-catalog/add/',
  path: '/course-catalog/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCatalogIdIndexRoute = CourseCatalogIdIndexRouteImport.update({
  id: '/course-catalog/$id/',
  path: '/course-catalog/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course-catalog/': typeof CourseCatalogIndexRoute
  '/student-list/': typeof StudentListIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/course-catalog/$id/': typeof CourseCatalogIdIndexRoute
  '/course-catalog/add/': typeof CourseCatalogAddIndexRoute
  '/student-list/$id/': typeof StudentListIdIndexRoute
  '/student-list/add/': typeof StudentListAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course-catalog': typeof CourseCatalogIndexRoute
  '/student-list': typeof StudentListIndexRoute
  '/weather': typeof WeatherIndexRoute
  '/course-catalog/$id': typeof CourseCatalogIdIndexRoute
  '/course-catalog/add': typeof CourseCatalogAddIndexRoute
  '/student-list/$id': typeof StudentListIdIndexRoute
  '/student-list/add': typeof StudentListAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course-catalog/': typeof CourseCatalogIndexRoute
  '/student-list/': typeof StudentListIndexRoute
  '/weather/': typeof WeatherIndexRoute
  '/course-catalog/$id/': typeof CourseCatalogIdIndexRoute
  '/course-catalog/add/': typeof CourseCatalogAddIndexRoute
  '/student-list/$id/': typeof StudentListIdIndexRoute
  '/student-list/add/': typeof StudentListAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/course-catalog/'
    | '/student-list/'
    | '/weather/'
    | '/course-catalog/$id/'
    | '/course-catalog/add/'
    | '/student-list/$id/'
    | '/student-list/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/course-catalog'
    | '/student-list'
    | '/weather'
    | '/course-catalog/$id'
    | '/course-catalog/add'
    | '/student-list/$id'
    | '/student-list/add'
  id:
    | '__root__'
    | '/'
    | '/course-catalog/'
    | '/student-list/'
    | '/weather/'
    | '/course-catalog/$id/'
    | '/course-catalog/add/'
    | '/student-list/$id/'
    | '/student-list/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseCatalogIndexRoute: typeof CourseCatalogIndexRoute
  StudentListIndexRoute: typeof StudentListIndexRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
  CourseCatalogIdIndexRoute: typeof CourseCatalogIdIndexRoute
  CourseCatalogAddIndexRoute: typeof CourseCatalogAddIndexRoute
  StudentListIdIndexRoute: typeof StudentListIdIndexRoute
  StudentListAddIndexRoute: typeof StudentListAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/weather'
      fullPath: '/weather/'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list/': {
      id: '/student-list/'
      path: '/student-list'
      fullPath: '/student-list/'
      preLoaderRoute: typeof StudentListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-catalog/': {
      id: '/course-catalog/'
      path: '/course-catalog'
      fullPath: '/course-catalog/'
      preLoaderRoute: typeof CourseCatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list/add/': {
      id: '/student-list/add/'
      path: '/student-list/add'
      fullPath: '/student-list/add/'
      preLoaderRoute: typeof StudentListAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-list/$id/': {
      id: '/student-list/$id/'
      path: '/student-list/$id'
      fullPath: '/student-list/$id/'
      preLoaderRoute: typeof StudentListIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-catalog/add/': {
      id: '/course-catalog/add/'
      path: '/course-catalog/add'
      fullPath: '/course-catalog/add/'
      preLoaderRoute: typeof CourseCatalogAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-catalog/$id/': {
      id: '/course-catalog/$id/'
      path: '/course-catalog/$id'
      fullPath: '/course-catalog/$id/'
      preLoaderRoute: typeof CourseCatalogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseCatalogIndexRoute: CourseCatalogIndexRoute,
  StudentListIndexRoute: StudentListIndexRoute,
  WeatherIndexRoute: WeatherIndexRoute,
  CourseCatalogIdIndexRoute: CourseCatalogIdIndexRoute,
  CourseCatalogAddIndexRoute: CourseCatalogAddIndexRoute,
  StudentListIdIndexRoute: StudentListIdIndexRoute,
  StudentListAddIndexRoute: StudentListAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
