// <auto-generated />
using System;
using Api.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407020850_SeedCourses")]
    partial class SeedCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Api.Web.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inserted")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 7),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 8),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 9),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 10),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 11),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 12),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 13),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 14),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 15),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 16),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 11,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 17),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Bracing",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = 12,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 18),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Hot",
                            TemperatureC = -14
                        },
                        new
                        {
                            Id = 13,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 19),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 14,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 20),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Hot",
                            TemperatureC = -17
                        },
                        new
                        {
                            Id = 15,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 21),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Scorching",
                            TemperatureC = -9
                        },
                        new
                        {
                            Id = 16,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 22),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = 31
                        },
                        new
                        {
                            Id = 17,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 23),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Freezing",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 18,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 24),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Warm",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = 19,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 25),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Freezing",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 20,
                            Archived = false,
                            Date = new DateOnly(2026, 4, 26),
                            Inserted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedBy = "",
                            Summary = "Sweltering",
                            TemperatureC = 20
                        });
                });

            modelBuilder.Entity("Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inserted")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weeks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Archived = false,
                            Credits = 3,
                            Description = "Fundamentals of programming and computational thinking.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Introduction to Computer Science",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            Credits = 3,
                            Description = "Arrays, linked lists, trees, graphs, and algorithm analysis.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Data Structures & Algorithms",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            Credits = 4,
                            Description = "Limits, derivatives, and an introduction to integration.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Calculus I",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            Credits = 3,
                            Description = "Vectors, matrices, eigenvalues, and linear transformations.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Linear Algebra",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            Credits = 3,
                            Description = "HTML, CSS, JavaScript, and modern frontend frameworks.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Web Development",
                            Weeks = 12
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            Credits = 3,
                            Description = "Relational databases, SQL, normalization, and query optimization.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Database Systems",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 8,
                            Archived = false,
                            Credits = 3,
                            Description = "Processes, memory management, file systems, and concurrency.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Operating Systems",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 9,
                            Archived = false,
                            Credits = 4,
                            Description = "Supervised and unsupervised learning, neural networks, and model evaluation.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Machine Learning",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 10,
                            Archived = false,
                            Credits = 3,
                            Description = "Agile methodologies, system design, testing, and project management.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Software Engineering",
                            Weeks = 16
                        },
                        new
                        {
                            Id = 11,
                            Archived = false,
                            Credits = 3,
                            Description = "TCP/IP, routing, protocols, and network security fundamentals.",
                            Inserted = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InsertedBy = "seed",
                            Name = "Computer Networks",
                            Weeks = 16
                        });
                });

            modelBuilder.Entity("Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inserted")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Inserted")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsertedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Course", b =>
                {
                    b.HasOne("Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId");

                    b.HasOne("Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
