// <auto-generated />
using System;
using Api.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Web.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Api.Web.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 4, 5),
                            Summary = "Bracing",
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 4, 6),
                            Summary = "Warm",
                            TemperatureC = -11
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 4, 7),
                            Summary = "Chilly",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 4, 8),
                            Summary = "Warm",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 4, 9),
                            Summary = "Hot",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2026, 4, 10),
                            Summary = "Chilly",
                            TemperatureC = -3
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2026, 4, 11),
                            Summary = "Cool",
                            TemperatureC = 17
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2026, 4, 12),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2026, 4, 13),
                            Summary = "Freezing",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2026, 4, 14),
                            Summary = "Warm",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2026, 4, 15),
                            Summary = "Bracing",
                            TemperatureC = 9
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2026, 4, 16),
                            Summary = "Hot",
                            TemperatureC = -14
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2026, 4, 17),
                            Summary = "Warm",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2026, 4, 18),
                            Summary = "Hot",
                            TemperatureC = -17
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2026, 4, 19),
                            Summary = "Scorching",
                            TemperatureC = -9
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2026, 4, 20),
                            Summary = "Warm",
                            TemperatureC = 31
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2026, 4, 21),
                            Summary = "Freezing",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2026, 4, 22),
                            Summary = "Warm",
                            TemperatureC = 3
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2026, 4, 23),
                            Summary = "Freezing",
                            TemperatureC = 41
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2026, 4, 24),
                            Summary = "Sweltering",
                            TemperatureC = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
